<?php
/** @var \Perspective\Them5ex1\Block\Template $block */
$viewModel = $block->getData('view_model');
//5.1.1
/**$productId = 2042; // YOUR PRODUCT ID
$product = $viewModel->getProductById($productId);
 
for current product
$product = $block->getCurrentProduct();
 
$categoryIds = $product->getCategoryIds();
 
$categories = $viewModel ->getCategoryCollection()->addAttributeToFilter('entity_id', $categoryIds);
                   
foreach ($categories as $category) {
    echo $category->getName() . '<br>';
}*/
// 5.1.2
/**$productId = [];
$catalogRule = $viewModel->getAllActiveCatalogRule();
foreach($catalogRule as $rule) {
    #var_dump($rule->getData());
    #echo ($rule->getId());
    #echo "<br>";
    $productId = $rule->getId();
    $product = $viewModel->getProductById($productId);
    echo $product->getName() . '<br>';
}*/
// 5.1.3
/**$ids = [1,2,3];
$categoryProducts = $viewModel->getProductCollectionByCategories($ids);
foreach ($categoryProducts as $product) {
    echo $product->getName() . ' - ' . $product->getProductUrl() . '<br />';
}
*/
// 5.1.4
$collection = $viewModel->getProductCollection();
foreach ($collection as $product) {
    echo $product->getName() . ' - ' . $product->getProductUrl() . '<br />';
}
?>
