<?php
/** @var \Perspective\Them5ex4\Block\Template $block */


$viewModel = $block->getData('view_model');
echo ('Bandle'. '<hr>');
 $items = $viewModel->getChildrenItems();
    foreach ($items as $item) {
        
        echo ($item->getData('sku') . "<br>");
    } 

   echo ("<br>".'Group'.'<hr>');   
$sku = '24-WG085_Group';
    $childProductsData = $viewModel->getChildItemsFromGroupedProduct($sku);
    foreach ($childProductsData as $childProduct) {
      
        echo ($childProduct->getData('sku') . "<br>");
    }
?>