<?php
/** @var \Perspective\Them5ex3\Block\Template $block */
$viewModel = $block->getData('view_model');
?>
<h3>Категория Woman-Tops-Jackets где цена от 50$ до 60$</h3>
<?php
$ids = 23;
$categoryProducts = $viewModel->getProductCollectionByCategories();
/* foreach ($categoryProducts as $product) {
    echo $categoryName . ' ';
    echo '<b>Name: </b>' . $product->getName() . '<br />';
    echo '<b>Price: </b>' . round($product->getData('price'),2) . ' $' . '<br />';
    echo '<b>Sku: </b>' . $product->getSku() . '<br />';
    echo '<br>'; 
}*/?>
 <table border='1'>
    <tr>
        <td><h3 style="color:red;">Название</h3></td>
        <td><h3 style="color:red;">SKU</h3></td>
        <td><h3 style="color:red;">Цена</h3></td>
    </tr>

<?php foreach ($categoryProducts as $product) : ?>
    <tr>
        <td><h3> <?= ($product->getData('name')); ?></h3></td>
        <td><h3> <?= ($product->getData('sku')); ?></h3></td>
        <td><h3> <?= (round($product->getData('price'), 2) . '$'); ?></h3></td>        
    </tr>
<?php endforeach; ?>

</table> 
