<?php
/** @var \Perspective\Them10ex1\Block\Template $block */

$viewModel = $block->getData('view_model');
$collection = $viewModel->getPostCollection();
/*  foreach ($collection as $item) {
    echo "<pre>";
    print_r($item->getProductId()) . '<br>';
    echo "</pre>";
}  */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$collection = $viewModel->getCollectionId();
$categoryId = 23;
$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory')->create();
$category = $categoryFactory->load($categoryId);
 
$products = $category->getProductCollection()
                    ->addAttributeToSelect('*');

foreach ($products as $product) {
    $productTemp = $product->getId();
    foreach ($collection as $item) {
        $productIdTemp = $item->getData("product_id");
        if ($productTemp !== $productIdTemp) 
        {

        } else {
            echo "Product ID: " . $item->getData("product_id") . "<br />";
            echo "Product Sku: " . $product->getData("sku") . "<br />";
            echo "Product Price: " . round($product->getData("price"),2) . " $<br />";
            echo "Product Category Name: " . $category->getData("url_key") . "<br />";
            echo "Product Review: " . $item->getData("text_rev") . "<br />";
            #echo "Product Url: " . $product->getProductUrl() . "<br />";
            $productImages = $viewModel->getProductImages($item->getData("product_id"));
            foreach ($productImages as $image) {
                echo "Product Url: " . $image->getUrl() . "<br/>";
                echo "<img src=" . $image->getUrl() . " width='150' height='150' />" . "<br/>";
            }
            #var_dump($product->getData());
        }
    };
}

?>